import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

const GoogleCallback: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    if (window) {
      fetch(
        `https://noobium.herokuapp.com/api/sign-in/google/callback${window.location.search}`,
        {
          headers: new Headers({
            accept: "application/json",
          }),
        }
      )
        .then((response) => {
          if (response.ok) {
            return response.json();
          }

          throw new Error("Something went wrong!");
        })
        .then((data) => {
          localStorage.setItem("access_token", data.data.access_token.token);
          router.replace("/dashboard");
        })
        .catch((error) => {
          console.error(error);
        });
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Redirecting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <p>Redirecting...</p>
      </div>
    </div>
  );
};

export default GoogleCallback;
