import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";

const Dashboard: NextPage = () => {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    const token = localStorage.getItem("access_token");

    if (token) {
      axios
        .get(`http://167.172.70.208:8001/api/me/profile`, {
          headers: {
            Accept: "application/json",
            Authorization: `Bearer ${token}`,
          },
        })
        .then((response) => {
          console.log(response);
          setUser(response.data.data);
        })
        .catch((error) => {
          console.error(error);
        });
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        {user ? (
          <>
            <img
              style={{
                width: 64,
                height: 64,
                borderRadius: 64,
                marginBottom: 24,
              }}
              src={user.picture}
              alt={user.name}
              referrerPolicy="no-referrer"
            />
            <p>{user.name}</p>
            <p>{user.email}</p>
          </>
        ) : (
          <p>Loading user...</p>
        )}
      </div>
    </div>
  );
};

export default Dashboard;
