import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";

const Dashboard: NextPage = () => {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    const token = localStorage.getItem("access_token");

    if (token) {
      fetch("https://noobium.herokuapp.com/api/me/profile", {
        headers: new Headers({
          accept: "application/json",
          authorization: `Bearer ${token}`,
        }),
      })
        .then((response) => {
          if (response.ok) {
            return response.json();
          }

          throw new Error("Something went wrong!");
        })
        .then((data) => {
          setUser(data.data);
        })
        .catch((error) => console.error(error));
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "100vh",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        {user ? (
          <>
            <img
              style={{
                width: 64,
                height: 64,
                borderRadius: 64,
                marginBottom: 24,
              }}
              src={user.picture}
              alt={user.name}
            />
            <p>{user.name}</p>
            <p>{user.email}</p>
          </>
        ) : (
          <p>Loading user...</p>
        )}
      </div>
    </div>
  );
};

export default Dashboard;
