import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [googleSignInURL, setGoogleSignInURL] = useState("");

  useEffect(() => {
    fetch("https://noobium.herokuapp.com/api/sign-in/google/get-url", {
      headers: new Headers({ accept: "application/json" }),
    })
      .then((response) => {
        if (response.ok) {
          return response.json();
        }

        throw new Error("Something went wrong!");
      })
      .then((data) => {
        setGoogleSignInURL(data.data.url);
      })
      .catch((error) => console.error(error));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        {googleSignInURL ? (
          <a href={googleSignInURL}>
            <button
              style={{
                fontSize: 16,
                padding: "16px 24px",
              }}
              type="button"
            >
              Login with Google
            </button>
          </a>
        ) : (
          <p>Please Wait...</p>
        )}
      </div>
    </div>
  );
};

export default Home;
