import type { NextPage } from "next";
import { useEffect, useRef } from "react";
import Head from "next/head";
import jwtDecode from "jwt-decode";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const refSignInWrapper = useRef(null);

  const handleCallbackResponse = (response) => {
    const data = jwtDecode(response.credential);

    const user = {
      id: data.sub,
      name: data.name,
      email: data.email,
      picture: data.picture,
    };

    console.clear();
    console.log(response.credential);
    console.log(user);
  };

  useEffect(() => {
    const clientId =
      "1037024452195-fd2m5nm03ucj6iu2ra4426dpqc7agts4.apps.googleusercontent.com";

    google.accounts.id.initialize({
      client_id: clientId,
      scope: [
        "https://www.googleapis.com/auth/userInfo.email",
        "https://www.googleapis.com/auth/userInfo.profile",
      ],
      callback: handleCallbackResponse,
    });

    google.accounts.id.renderButton(refSignInWrapper.current, {
      theme: "outline",
      size: "large",
      shape: "pill",
      width: 400,
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://accounts.google.com/gsi/client" async defer />
      </Head>

      <div
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <div ref={refSignInWrapper} />
      </div>
    </div>
  );
};

export default Home;
