import type { NextPage } from "next";
import { useEffect, useRef } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import axios from "axios";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const refSignInWrapper = useRef(null);
  const router = useRouter();

  const handleCallbackResponse = (response) => {
    // TODO: From here you can handle the access token from Google.

    axios
      .post(
        `http://167.172.70.208:8001/api/sign-in/google`,
        {
          token: response.credential,
        },
        {
          headers: {
            Accept: "application/json",
          },
        }
      )
      .then((response) => {
        localStorage.setItem(
          "access_token",
          response.data.data.access_token.token
        );

        router.replace("/dashboard");
      })
      .catch((error) => {
        console.error(error);
      });
  };

  useEffect(() => {
    const clientId =
      "1037024452195-fd2m5nm03ucj6iu2ra4426dpqc7agts4.apps.googleusercontent.com";

    google.accounts.id.initialize({
      client_id: clientId,
      callback: handleCallbackResponse,
    });

    google.accounts.id.renderButton(refSignInWrapper.current, {
      theme: "outline",
      size: "large",
      shape: "pill",
      width: 400,
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://accounts.google.com/gsi/client" async defer />
      </Head>

      <div
        style={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <div ref={refSignInWrapper} />
      </div>
    </div>
  );
};

export default Home;
